name: fly_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - matplotlib
  - h5py
  - opencv
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - pip
  - pip:
    - jupyterlab
    - tqdm